# Generated by Django 5.2.4 on 2025-07-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="isDiscounted",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
